services:
  web:
    build: .

    ports:
      - '8000:8000'

    env_file:
      - .env

    volumes:
      - ./data:/app/data

  db:
    image: postgres:17

    ports:
      - '5434:5432'

    env_file:
      - .env.db

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: