"""Upgrade models

Revision ID: 839bd9d9e756
Revises: a2165bedd219
Create Date: 2025-09-03 21:27:18.752996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839bd9d9e756'
down_revision: Union[str, Sequence[str], None] = 'a2165bedd219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum('user', 'manager', 'admin', name='userrole')
file_visibility_enum = sa.Enum('private', 'department', 'public', name='filevisibility')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind())
    file_visibility_enum.create(op.get_bind())

    op.add_column('files', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('author', sa.String(), nullable=True))
    op.alter_column('files', 'visibility',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PRIVATE', 'DEPARTMENT', 'PUBLIC', name='filevisibility'),
               nullable=False,
               postgresql_using='visibility::filevisibility')
    op.create_unique_constraint(None, 'files', ['s3_path'])
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'MANAGER', 'ADMIN', name='userrole'), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.drop(op.get_bind())
    file_visibility_enum.drop(op.get_bind())
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'files', type_='unique')
    op.alter_column('files', 'visibility',
               existing_type=sa.Enum('PRIVATE', 'DEPARTMENT', 'PUBLIC', name='filevisibility'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'author')
    op.drop_column('files', 'page_count')
    # ### end Alembic commands ###
