"""Migrate for add admin

Revision ID: 88b7e2421a31
Revises: 839bd9d9e756
Create Date: 2025-09-03 21:37:29.121213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.security import hash_password


# revision identifiers, used by Alembic.
revision: str = '88b7e2421a31'
down_revision: Union[str, Sequence[str], None] = '839bd9d9e756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    departments_table = sa.table('departments',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String)
    )

    op.bulk_insert(departments_table,
        [
            {'id': 1, 'name': 'IT Department'},
            {'id': 2, 'name': 'HR Department'},
            {'id': 3, 'name': 'Management'}
        ]
    )

    users_table = sa.table('users',
        sa.column('id', sa.Integer),
        sa.column('username', sa.String),
        sa.column('password_hash', sa.String),
        sa.column('role', sa.String), 
        sa.column('department_id', sa.Integer)
    )

    op.bulk_insert(users_table,
        [
            {
                'id': 1, 
                'username': 'admin',
                
                'password_hash': hash_password('admin'), 
                'role': 'admin', 
                'department_id': 1
            },
            {
                'id': 2,
                'username': 'manager',
                'password_hash': hash_password('manager'), 
                'role': 'manager',
                'department_id': 2 
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE username = 'admin'")
    op.execute("DELETE FROM departments WHERE name IN ('IT Department', 'HR Department', 'Management')")
    # ### end Alembic commands ###
