"""Add admin and manager

Revision ID: 8d8bae8ea00d
Revises: 2e054cebb029
Create Date: 2025-09-04 17:00:33.018847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.security import hash_password


# revision identifiers, used by Alembic.
revision: str = '8d8bae8ea00d'
down_revision: Union[str, Sequence[str], None] = '2e054cebb029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    departments_table = sa.table('departments',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String)
    )
    op.bulk_insert(departments_table,
        [
            {'id': 1, 'name': 'IT Department'},
            {'id': 2, 'name': 'HR Department'},
            {'id': 3, 'name': 'Management'},
        ]
    )

    
    admin_password_hash = hash_password('admin').replace("'", "''")
    manager_password_hash = hash_password('manager').replace("'", "''")

    op.execute(f"""
        INSERT INTO users (id, username, password_hash, role, department_id)
        VALUES
            (1, 'admin', '{admin_password_hash}', 'ADMIN'::userrole, 1),
            (2, 'manager', '{manager_password_hash}', 'MANAGER'::userrole, 2);
    """)

    
    op.execute("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE username IN ('admin', 'manager')")
    op.execute("DELETE FROM departments WHERE name IN ('IT Department', 'HR Department', 'Management')")
    # ### end Alembic commands ###
