"""Added metadata to File model

Revision ID: e9f7c01b7a9a
Revises: 8d8bae8ea00d
Create Date: 2025-09-06 06:52:41.525411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9f7c01b7a9a"
down_revision: Union[str, Sequence[str], None] = "8d8bae8ea00d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("title", sa.String(), nullable=True))
    op.add_column("files", sa.Column("created_date", sa.String(), nullable=True))
    op.add_column("files", sa.Column("creator_tool", sa.String(), nullable=True))
    op.add_column("files", sa.Column("paragraph_count", sa.Integer(), nullable=True))
    op.add_column("files", sa.Column("table_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "table_count")
    op.drop_column("files", "paragraph_count")
    op.drop_column("files", "creator_tool")
    op.drop_column("files", "created_date")
    op.drop_column("files", "title")
    # ### end Alembic commands ###
